inherit_from: .rubocop_todo.yml
# 自動生成されるものはチェック対象から除外する
AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - "node_modules/**/*"
    - "vendor/**/*"
    - "db/schema.rb"
    - "db/seeds.rb"

# 日本語でのコメントを許可
AsciiComments:
  Enabled: false

# 行末のカンマを許可
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

# 1行の長さ
Metrics/LineLength:
  Exclude:
    - 'db/**/*'
    - 'config/initializers/*'
    - 'bin/*'
    - 'lib/tasks/auto_annotate_models.rake'

Metrics/BlockLength:
  Exclude:
    - 'db/schema.rb'
    - 'app/admin/*'
    - 'config/routes.rb'
    - "Rakefile"
    - "**/*.rake"
    - "spec/**/*.rb"
    - "Gemfile"
    - "Guardfile"
    - "config/environments/*.rb"
    - "config/routes.rb"
    - "config/routes/**/*.rb"
    - "*.gemspec"

# # 複数行での「lambda」で「->」による省略記法を許可
# Lambda:
#   Enabled: false

# モジュール名::クラス名の定義を許可
ClassAndModuleChildren:
  Enabled: false

# # メソッド名のprefixに「set_」「get_」を許可
# AccessorMethodName:
#   Enabled: false

# # クラスにコメントを許可
Documentation:
  Enabled: false

# # 「and」「or」の使用を許可
# AndOr:
#   Enabled: false

# AllCops:
#   Exclude:
#     - db/schema.rb
#     - config/unicorn.rb
#     - config/unicorn_staging.rb
#     - tmp/**/*